version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 99
  versioning-strategy: increase
  ignore:
  - dependency-type: "development"
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 99
  ignore:
    - dependency-name: "nova"
